CREATE DATABASE ContactsDB
CHARACTER SET utf8
COLLATE utf8_spanish2_ci;

--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.597.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/07/2021 11:01:16
-- Server version: 10.5.9
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE ContactsDB;

--
-- Drop table `Contacts`
--
DROP TABLE IF EXISTS Contacts;

--
-- Set default database
--
USE ContactsDB;

--
-- Create table `Contacts`
--
CREATE TABLE Contacts (
  Id int(11) NOT NULL AUTO_INCREMENT,
  FirstName varchar(100) NOT NULL,
  LastName varchar(100) NOT NULL,
  Phone varchar(50) DEFAULT NULL,
  Address varchar(100) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8,
COLLATE utf8_spanish_ci;

-- 
-- Dumping data for table Contacts
--
INSERT INTO Contacts VALUES
(1, 'Jorge', 'Zurita', '932192525', 'Carrer de Casi Miro 9o B');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;