version: '3.4'
services: 
  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    volumes:
      - ./mariadb:/var/lib/mysql
      - ./conf:/etc/mysql


